### PR TITLE
Fixed xcb-ewmh window position

### PR DESCRIPTION
**Pull request by kjdev**
In environment (Fedora 24) `position: "bottom"` even has been displayed on the top.

### CODE REVIEW

**Comment by geommer** [comment]
Thanks @kjdev for your effort with all these requests. For this one, since I use Archlinux, I just fail to understand what the extra 2 lines `in ya_execute()` do. Why isn't the code in `ya_create_bar()` sufficient for the top and bottom cases? it has been working well for my machine since the beginning. But I can't understand why it is not working for you. What window manager are you using?

**Comment by kjdev** [comment]
Environment:

* OS : Fedora24
* WM : OpenBox (3.6.1)
* xcb-util-wm: 0.4.1

If no failure has occurred, it is may not be modified so only my environment.

**Comment by Narrat** [comment]
Just as a note. I will check if this PR will help with #96

**Comment by ibrokemypie** [comment]
thank you so much, this fixes the issue perfectly! @geommer are you still working on yabar? perhaps adding @kjdev as a colaborator would be good, so that he could merge these pulls requests and make it easier for users to get an updated app?

**Comment by geommer** [comment]
Sorry for being so late, to be merged.

**Pull request merged**
