### PR TITLE
Added some error handling. Fixes #17

### LINKED ISSUE #17: Completion of error handling
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [ya_setup_block](https://github.com/geommer/yabar/blob/5fcc0114354feebe90a7afe81d68791d8dad8f5c/src/ya_exec.c#L234)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [ya_init](https://github.com/geommer/yabar/blob/5fcc0114354feebe90a7afe81d68791d8dad8f5c/src/ya_exec.c#L122)

### PR DESCRIPTION
**Pull request by Lindenk**
Added error handling for a calloc call and registering signal handlers. Fixes #17.

### CODE REVIEW

**Comment by geommer** [comment]
Thanks @Lindenk, I just need to know about what `on_signal_register_error` is and what it does. Can't we just handle `SIG_ERR` using `perror("blabla");exit(EXIT_FAILURE);`?

**Comment by Lindenk** [comment]
Right, I forgot about `perror`. I guess it's been awhile since I've written much in C. The function was just to consolidate the error code but your solution sounds better.

**Comment by geommer** [comment]
That is okay, I will do it. For the calloc handling, I am not very convinced that dynamic allocation functions still fail in 2016 :smile: .

**Comment by Lindenk** [comment]
Probably not :smile:. I guess you could make a case for embedded devices, but then again, I'm not sure you'd be running a GUI on it with yabar if it couldn't handle it.

**Pull request closed without merging**
